id: spark-master-bunk
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: spark
    containers:
      - name: spark
        image: jayunit100/spark7
        bcommand:
           - /bin/bash
           - /opt/run.sh
           - master
        bcpu: 1000
        bports:
          - name: spark-master
            containerPort: 7077
labels:
  name: spark-master

