VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "jayunit100/centos7"
  config.vm.provision "docker"
  config.vm.provision "shell", inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
  config.vm.provision "shell", inline: "yum install -y git && service firewalld stop && service docker restart"  
  config.vm.network :forwarded_port, guest: 3000, host: 3000

end
